### ISSUE TITLE
UI needs some extra spacing

### ISSUE THREAD

**Issue by OutdatedGuy** [malivinayak/Alarm-Clock#1]
Great project and good UI.

Just my _personal_ opinion that there should be some appropriate space between select fields

<img width="510" alt="image" src="https://user-images.githubusercontent.com/74326345/201287050-24c4a6c8-8e73-4a81-b693-74036bba1f1b.png">

**Comment by malivinayak** [comment]
I will definitely Consider it

**Comment by OutdatedGuy** [comment]
@malivinayak any updates?

**Comment by malivinayak** [comment]
tried but not getting
PR is welcome

**Comment by OutdatedGuy** [comment]
> tried but not getting PR is welcome

@malivinayak, just add `column-gap: 10px;` to the `content` class
