### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by Mouli-3542** [malivinayak/Alarm-Clock#3]
I want to contribute in this ....any basic issues i can work on @malivinayak

**Comment by malivinayak** [comment]
You can work on #1 
Its a simpler issue you can easily fix it 
solution is also provided at https://github.com/malivinayak/Alarm-Clock/issues/1#issuecomment-1556004950

**Comment by malivinayak** [comment]
> You can work on https://github.com/malivinayak/Alarm-Clock/issues/1
>

PR Done at #6
